# Generated by Django 2.0 on 2020-02-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('util', models.IntegerField(max_length=32, verbose_name='磁盘使用率')),
                ('iowait', models.IntegerField(max_length=32, verbose_name='等待磁盘IO响应使用率')),
            ],
        ),
    ]
