# Generated by Django 2.0 on 2020-02-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='iowait',
            field=models.IntegerField(verbose_name='等待磁盘IO响应使用率'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='util',
            field=models.IntegerField(verbose_name='磁盘使用率'),
        ),
    ]
