# Generated by Django 2.0 on 2020-02-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performa', '0002_auto_20200224_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='time',
            field=models.IntegerField(default=0, verbose_name='执行时间'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cpu',
            table='cpu',
        ),
    ]
