# Generated by Django 2.0 on 2020-02-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performa', '0003_auto_20200224_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='time',
            new_name='execution',
        ),
    ]
